### ISSUE TITLE
Hidden overflow on collapsed inputfield cuts off edit field link

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#107]
The CSS rule...

```css
html.aos .InputfieldStateCollapsed {
    overflow: hidden!important;
}
```
...causes the edit field link to be cut off.

![2019-03-18_140206](https://user-images.githubusercontent.com/1538852/54500936-dfc22a00-4986-11e9-84d2-c1be4dfda79a.png)

I removed this rule and things seem to work okay without it, but I didn't do a heap of testing and I'm sure you must have added it for some reason. Maybe some other solution can be found, e.g. hiding overflow more specifically for `.InputfieldStateCollapsed .InputfieldContent`?
