### ISSUE TITLE
GraphQL Monospace Font Issue - .CodeMirror-lines *

### ISSUE THREAD

**Issue by brettwilcox** [rolandtoth/AdminOnSteroids#119]
I am having an issue with the following CSS where it is causing GraphQL to use use a non monospace font without any way to override that I can find. I would like to see the !important removed from everything in this style so I can override.

```css
.CodeMirror-lines * {
  font-size: 0.96rem !important;
  font-family: -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    Roboto,
    "Helvetica Neue",
    Arial,
    sans-serif !important;
}
```
