### ISSUE TITLE
InputfieldCheckbox on AdminThemeUikit has display problems

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#59]
![edit page about us pwoliver test 2017-10-02 09-26-18](https://user-images.githubusercontent.com/40570/31082215-eec8e2a4-a753-11e7-830a-3cf5971a15f1.jpg)

The screenshot shows how the field label doesn't fully span width, so only the label is clickable not the full row.

I think this css rule is causing the issue even when AOS tooltips submodule is disabled:
```css
.aos_hasTooltip .title, .InputfieldCheckbox label {
    position: relative;
    display: inline-block;
}
```

**Comment by gmclelland** [comment]
Ok, with the latest update to AdminThemeUikit, the label spans the full width now, but it's missing the borders.

To bring back the borders, I had to do the following:
```css
/* Modified Existing CSS Rule */
html.aos .InputfieldStateCollapsed, html.aos .InputfieldStateWasCollapsed {
    overflow: visible !important;
    position: relative; /*added this*/
}

/* New CSS Rule */
.aos_hasTooltip{
  position:relative;
}
```

This seems to work on the AdminThemeUikit and the Classic theme.

Hope that helps
