### ISSUE TITLE
AOS with AdminThemeUikit prevents new page from Publishing

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#61]
This only happens when a brand new page is created and needs to be published.

Here is a screenshot of the top "Publish" button
![edit page test pwoliver dev 2017-10-02 12-04-03](https://user-images.githubusercontent.com/40570/31089501-f578d7c4-a769-11e7-8e40-339cb9462ffd.jpg)

Note: the bottom "Publish" button works just fine.
![edit page test pwoliver dev 2017-10-02 12-05-49](https://user-images.githubusercontent.com/40570/31089534-1efbe7f8-a76a-11e7-8e3d-e64113182521.jpg)

**Comment by gmclelland** [comment]
Ok, I found the problem.

If you disable the rules in the red box, everything starts to work correctly.

```css
html.aos h1:not(.pwapi-headline) {
    position: relative;
}
html.aos h1 {
    max-width: calc(100% - 120px);
}
```

![edit page hello pwoliver dev 2017-10-05 15-37-59](https://user-images.githubusercontent.com/40570/31251413-7a59cedc-a9e3-11e7-99d0-c440cf4d4fd8.jpg)

I'm not sure what those rules are for, but it doesn't appear to cause any problems with the Classic, Reno, or AdminThemeUikit when I disable them.

Hope that helps
