### ISSUE TITLE
AdminThemeUikit - Image fields size information overlaps download icon

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#63]
![edit page outdoor adventures pwoliver dev 2017-10-02 12-13-40](https://user-images.githubusercontent.com/40570/31089895-59061d32-a76b-11e7-96e2-1f26772dd49d.jpg)

**Comment by gmclelland** [comment]
Looks like this happens with the Classic theme as well.

I think the fix is to remove:
```css
.aos_downloadAsset {
    position: absolute;
    z-index: 99;
}
```
