### ISSUE TITLE
Different size buttons when editing a page

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#80]
I noticed a minor styling issue with the button heights:
![edit page](https://user-images.githubusercontent.com/40570/33774576-54aa1b2e-dc01-11e7-92e7-2a2a733c240f.jpg)

This can be solved in the AdminThemeUikit by adding:
```css
border: none;
```
to
```css
html.hoverDropdown .ui-button.pw-button-dropdown-main {
    border-radius: 4px !important;
}
```
But... it causes problems with the Default classic theme.  So I'm not sure yet how to fix it in a way that works across all themes.

I only noticed it because I just installed ProDrafts.

Note: this happens on the top and bottom buttons only on AdminThemeUikit, the other core theme's look fine.
