### ISSUE TITLE
Button spacing

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#89]
Just noticed the latest versions seems to make the buttons to close together.

![buttons](https://user-images.githubusercontent.com/40570/37349306-1ae1c2c8-26a4-11e8-8dfe-4837580798c2.jpg)

**Comment by gmclelland** [comment]
That is the bottom buttons on page edit.

**Comment by rolandtoth** [comment]
Could you post a CSS snippet to fix? I don't have ProDraft (I guess it's that on the image you posted). Or is it another example where I can have look?

**Comment by gmclelland** [comment]
It looks the only way to fix this is to add the following to AOS's css:
```css
/* override AdminThemeUiKit css so the page edit hover dropdown buttons don't touch together */
.hoverDropdown .AdminThemeUikit button.ui-button.pw-button-dropdown-main {
  margin-right:10px !important;
}

/* override the rule above so page edit head hover dropdown buttons don't space out to much */
.hoverDropdown .AdminThemeUikit #pw-content-head-buttons .ui-button {
  margin-right: 0 !important;
}
```
I don't like using !important, but it was the only way to override AdminThemeUikit's !important
